basler_params:
  -
    name: AcquisitionFrameRate
    type: float
    value: 60.0
  -
    name: AcquisitionFrameRateEnable
    type: boolean
    value: true
  -
    name: AcquisitionMode
    type: enum
    value: Continuous
  -
    name: ExposureAuto
    type: enum
    value: Continuous
